# Generated by Django 3.2.9 on 2021-11-22 11:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_order_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_order_status', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
                ('products', models.ManyToManyField(blank=True, null=True, to='Products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('sale_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_order_date', models.DateTimeField(blank=True, null=True)),
                ('sale_order_status', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transactions.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptOrder',
            fields=[
                ('receipt_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_order_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
                ('sale_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transactions.saleorder')),
            ],
        ),
    ]
